import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Fix: Restore pgvector column type on document_embeddings.embedding.
 *
 * The AddHintSystem migration auto-generated by TypeORM replaced
 * `vector(768)` with `double precision array`, breaking the `<=>` cosine
 * distance operator. This migration drops the broken column and recreates
 * it as `vector(3072)` to match the gemini-embedding-001 output dimensions.
 */
export class FixVectorColumnType1773100000000 implements MigrationInterface {
    name = 'FixVectorColumnType1773100000000';

    public async up(queryRunner: QueryRunner): Promise<void> {
        // Ensure pgvector extension exists (idempotent)
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS vector`);

        // Drop the broken double precision[] column and recreate as vector(3072)
        await queryRunner.query(
            `ALTER TABLE "document_embeddings" DROP COLUMN IF EXISTS "embedding"`,
        );
        await queryRunner.query(
            `ALTER TABLE "document_embeddings" ADD COLUMN "embedding" vector(3072) DEFAULT NULL`,
        );
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // Revert to double precision array (the broken state)
        await queryRunner.query(
            `ALTER TABLE "document_embeddings" DROP COLUMN IF EXISTS "embedding"`,
        );
        await queryRunner.query(
            `ALTER TABLE "document_embeddings" ADD COLUMN "embedding" double precision array`,
        );
    }
}
