/**
 * Security event types for audit logging.
 */
export enum SecurityEventType {
    // Authentication events
    LOGIN_SUCCESS = 'LOGIN_SUCCESS',
    LOGIN_FAILED = 'LOGIN_FAILED',
    LOGOUT = 'LOGOUT',
    LOGOUT_ALL = 'LOGOUT_ALL',

    // Password events
    PASSWORD_CHANGE = 'PASSWORD_CHANGE',
    PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST',
    PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS',

    // Email events
    EMAIL_VERIFICATION_SENT = 'EMAIL_VERIFICATION_SENT',
    EMAIL_VERIFIED = 'EMAIL_VERIFIED',

    // Session events
    SESSION_CREATED = 'SESSION_CREATED',
    SESSION_REVOKED = 'SESSION_REVOKED',
    SESSION_EXPIRED = 'SESSION_EXPIRED',
    TOKEN_REFRESHED = 'TOKEN_REFRESHED',

    // OAuth events
    OAUTH_LINK = 'OAUTH_LINK',
    OAUTH_UNLINK = 'OAUTH_UNLINK',

    // Account events
    ACCOUNT_SUSPENDED = 'ACCOUNT_SUSPENDED',
    ACCOUNT_DELETED = 'ACCOUNT_DELETED',
    ACCOUNT_RESTORED = 'ACCOUNT_RESTORED',

    // Security alerts
    NEW_DEVICE_LOGIN = 'NEW_DEVICE_LOGIN',
    SUSPICIOUS_ACTIVITY = 'SUSPICIOUS_ACTIVITY',
}
